# Generated by Django 3.2.9 on 2025-07-31 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_damageevaluation_otphoto_otstatushistory_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='asesor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'asesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asesor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'rol': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
