# Generated by Django 3.2.9 on 2025-08-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20250731_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='internamiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='tipo_cliente',
            field=models.CharField(choices=[('particular', 'Particular'), ('asegurado', 'Asegurado')], default='asegurado', max_length=20),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='estado',
            field=models.CharField(choices=[('recepcion', 'Recepción'), ('diagnostico', 'Diagnóstico'), ('cotizacion', 'Cotización'), ('aprobada', 'Aprobada'), ('taller', 'En Taller'), ('qc', 'Control Calidad'), ('listo', 'Listo para Entregar'), ('entregado', 'Entregado'), ('cerrado', 'Cerrado')], default='recepcion', max_length=20),
        ),
    ]
