# Generated by Django 3.2.9 on 2025-08-04 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_auto_20250804_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='damageevaluation',
            old_name='fecha',
            new_name='creado_en',
        ),
        migrations.AddField(
            model_name='damageevaluation',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='damageevaluation',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='damageevaluation',
            name='ot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='orders.workorder'),
        ),
        migrations.AlterField(
            model_name='damageevaluation',
            name='tecnico',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__in': ['tecnico', 'asesor', 'supervisor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
