# Generated by Django 3.2.9 on 2025-08-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20250804_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otphoto',
            old_name='tecnico',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='otphoto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otphoto',
            name='imagen',
            field=models.ImageField(upload_to='fotos_ots/'),
        ),
        migrations.AlterField(
            model_name='otphoto',
            name='tipo',
            field=models.CharField(choices=[('inicio', 'Inicio'), ('avance', 'Avance'), ('qc', 'Control de Calidad'), ('final', 'Final'), ('otro', 'Otro')], max_length=20),
        ),
    ]
