# Generated by Django 3.2.9 on 2025-08-04 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20250804_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otstatushistory',
            options={},
        ),
        migrations.RenameField(
            model_name='otstatushistory',
            old_name='timestamp',
            new_name='fecha_cambio',
        ),
        migrations.AddField(
            model_name='otstatushistory',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otstatushistory',
            name='ot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estado', to='orders.workorder'),
        ),
    ]
