# Generated by Django 3.2.9 on 2025-08-07 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0007_auto_20250804_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='activa',
            new_name='es_aprobada',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='pdf',
        ),
        migrations.AddField(
            model_name='quotation',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='cotizaciones/'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='descripcion',
            field=models.TextField(blank=True, default='Sin descripción'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='version',
            field=models.IntegerField(),
        ),
    ]
