# Generated by Django 3.2.9 on 2025-08-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='tipo',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('minivan', 'Minivan'), ('camioneta', 'Camioneta'), ('furgon', 'Furgon'), ('hatchback', 'Hatchback')], max_length=20),
        ),
    ]
