# Imagen base de Python
FROM python:3.12

# Instalar las dependencias necesarias para mysqlclient
RUN apt-get update && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo de requerimientos
COPY ./backend/requirements.txt /app/requirements.txt

# Instala las dependencias del proyecto
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copia el resto de los archivos del proyecto al contenedor
COPY ./backend /app/

# Copia el script wait-for-it y le da permisos de ejecución
COPY ./backend/wait-for-it.sh /app/wait-for-it.sh
RUN chmod +x /app/wait-for-it.sh

# Expone el puerto de Django
EXPOSE 8000
